#!/bin/sh
# Ant startup script adapted from the FreeBSD Port System.
# See: http://jakarta.apache.org/ant/
#

# You may need to change these values to suit your own installation for
# testing, but don't commit them to CVS before testing on the sourceforge
# servers
DEFAULT_JAVACMD=/usr/bin/java
DEFAULT_JAVA_HOME=/usr/java/j2re1.4.0_01
ANT_HOME=/home/groups/x/xm/xmlresume/resume-support/ant

#-----------------------------------------------------------------------------
# Determine configuration settings
#-----------------------------------------------------------------------------

# Determine the JDK home directory
if [ -z "${JAVA_HOME}" ]; then
	JAVA_HOME=${DEFAULT_JAVA_HOME}
fi

# Set ANT_LIB location
ANT_LIB="${ANT_HOME}/lib"

# Determine 'java' executable
if [ -z "${JAVACMD}" ]; then 
	if [ -n "${JAVA_HOME}"  ]; then
		JAVACMD="${JAVA_HOME}/bin/java"
	else
		JAVACMD=${DEFAULT_JAVACMD}
	fi
fi
 
# Check if 'java' executable can be found
if [ ! -x "$JAVACMD" ]; then
	echo "Error: JAVA_HOME is not defined correctly: ${JAVA_HOME}"
	echo "       Unable to find ${JAVACMD}"
	exit 1
fi


#-----------------------------------------------------------------------------
# Determine CLASSPATH
#-----------------------------------------------------------------------------

# Initialize the classpath to the existing classpath
if [ -n "$CLASSPATH" ]; then
	LOCALCLASSPATH="${CLASSPATH}"
fi

# Add the dependency .jar files from ${ANT_HOME}/lib
for JAR_FILE in "${ANT_LIB}"/*.jar; do

	# If the directory is empty, then the input string is returned
	if [ -f "${JAR_FILE}" ]; then
		if [ -z "$LOCALCLASSPATH" ]; then
			LOCALCLASSPATH="${JAR_FILE}"
		else
			LOCALCLASSPATH="${JAR_FILE}":"$LOCALCLASSPATH"
		fi
	fi
done

# Add the JDK tools.jar or classes.zip file to the CLASSPATH
if [ -n "${JAVA_HOME}" ]; then
	if [ -f "${JAVA_HOME}/lib/tools.jar" ]; then
		LOCALCLASSPATH="${LOCALCLASSPATH}:${JAVA_HOME}/lib/tools.jar"
	elif [ -f "${JAVA_HOME}/lib/classes.zip" ]; then
		LOCALCLASSPATH="${LOCALCLASSPATH}:${JAVA_HOME}/lib/classes.zip"
	fi
else
	echo "Warning: JAVA_HOME environment variable is not set."
	echo "  If build fails because sun.* classes could not be found"
	echo "  you will need to set the JAVA_HOME environment variable"
	echo "  to the installation directory of java."
fi


#-----------------------------------------------------------------------------
# Determine all Ant options
#-----------------------------------------------------------------------------

# Add option for the CLASSPATH
ANT_OPTS="${ANT_OPTS} -classpath ${LOCALCLASSPATH}"

# Add option for Ant home directory
ANT_OPTS="${ANT_OPTS} -Dant.home=${ANT_HOME}"

#-----------------------------------------------------------------------------
# Call Ant
#-----------------------------------------------------------------------------

if [ -n "${VERBOSE_ANT_SCRIPT}" ]; then
	echo "Java command: ${JAVACMD}"
	echo "Ant options: ${ANT_OPTS}"
	echo "Ant arguments: ${ANT_ARGS}"
fi

${JAVACMD} ${ANT_OPTS} org.apache.tools.ant.Main ${ANT_ARGS} $@

